### PR TITLE
Optimize log factory detection (#192)

### PR DESCRIPTION
**Pull request by Vampire**
Fixes LOGGING-192

### CODE REVIEW

**Comment by garydgregory** [comment]
Hello @Vampire,

Thank you for your PR.
Builds are failing.
Please rebase on master to pick up the GH CO Java 22 and experimental Java 23-ea builds

**Comment by Vampire** [comment]
Done, please re-approve

**Comment by garydgregory** [comment]
Hello @Vampire 
Thank you for your update.

Still build failures. You should probably test locally before pushing to avoid looping on build approvals. That would be quicker IMO.

**Comment by Vampire** [comment]
Definitely.
And before I first sent the PR, I did `mvn verify` which succeeded without problems.
I'm not a newbie in the FOSS world, you know? ;-)
I now also did the `mvn` that i just now have seen in the readme.
But also that succeeds without problems.
So it is a bit harsh to just assume I send untested changes, even if it occasionally happens. ;-)

I can hardly guess that it is not failing just because of the Java version and that I should try with other Java versions,
especially as you said "there was an upstream problem, please rebase and push again", making me assume it was not my fault that the build errored out.

**Comment by ppkarwasz** [comment]
The test that is failing uses a restrictive `SecurityManager`, so:

- `baseClassLoader` becomes `null` (retrieving the TCCL is not allowed)
- `isClassAvailable` fails, since calling `Class.forName` with a `null` classloader requires additional privileges.

**Comment by Vampire** [comment]
As the other PR contains the change I did here semantically, I think the changes are fine and should solve the problem.
I have a slight improvement to suggest and a logging that also previously was wrong.
See the updated changes here. :-)

**Review by ppkarwasz — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
