### PR TITLE
Remove references to very old JDK and commons logging versions

### PR DESCRIPTION
**Pull request by elharo**
I think it's safe to assume everyone is on Java 1.5 or later at this point.

### CODE REVIEW

**Comment by garydgregory** [comment]
Note this component's requirement is Java 8 like most of Commons.

**Comment by garydgregory** [comment]
CC: @ppkarwasz 
How does this look to you?

**Comment by ppkarwasz** [comment]
I think these days we can assume that:

- people run Java 8: the Java 7 Oracle Extended Support ended in July 2022,
- we can remove the section about serialization and deprecated properties. Deprecated properties might be described in a separate section in case someone already uses a deprecated property and he is wondering why does it work.

**Comment by elharo** [comment]
For further changes, please file an issue in Jira. If these changes look good, we can merge them and then proceed with others in future PRs.

**Review by ppkarwasz — APPROVED** [review]
LGTM

**Pull request merged**
